import Head from 'next/head'
import useSWR from 'swr'
import Person from '../components/Person'
import WizardForm from './WizardForm/index'

const fetcher = (url) => fetch(url).then((res) => res.json())

export default function Home() {
    const { data, error } = useSWR('/api/people', fetcher)

    if (error) return <div>Failed to load</div>
    if (!data) return <div>Loading...</div>

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <>
                <WizardForm/>
                <div>
                    {data.map((p, i) => (
                        <Person key={i} person={p} />
                    ))}
                </div>
            </>
        </>
    )
}