export const establishments = [
  {
    id: '01',
    name: 'the-lorem-inn',
    type: 'hotel',
    iconOne: 'fa-solid fa-spa',
    txtOne: 'Spa',
    iconTwo: 'fa-solid fa-newspaper',
    txtTwo: 'Free Newspaper',
    email: 'lorem@inn.com',
    price: '330',
    maxGuests: '4',
    imgURL: 'https://images.unsplash.com/photo-1529169436040-836f3d93f0f8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTE0fHxob3RlbHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=600&q=60',
    descriptionShort: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...',
    descriptionLong: 'Feugiat in fermentum posuere urna nec tincidunt praesent semper feugiat. Sed ullamcorper morbi tincidunt ornare. In ornare quam viverra orci sagittis eu volutpat odio facilisis. Viverra accumsan in nisl nisi scelerisque. Amet luctus venenatis lectus magna. Suspendisse in est ante in. Cras adipiscing enim eu turpis egestas pretium aenean. Condimentum vitae sapien pellentesque habitant morbi. Massa id neque aliquam vestibulum morbi blandit cursus. Sed faucibus turpis in eu mi. Mattis nunc sed blandit libero volutpat. Id diam maecenas ultricies mi eget mauris. Pretium lectus quam id leo. Laoreet non curabitur gravida arcu ac tortor. Pretium viverra suspendisse potenti nullam. Mi sit amet mauris commodo quis imperdiet massa. Sem viverra aliquet eget sit amet tellus. Velit euismod in pellentesque massa placerat duis ultricies lacus',
    address: '',
    location: 'Bergen city center',
    long: '',
    lat: '',
    stars: 'five',
  }, {
    id: '02',
    name: 'the-ipsum-inn',
    type: 'Hostel',
    iconOne: '',
    txtOne: '',
    iconTwo: '',
    txtTwo: '',
    email: 'ipsum@inn.com',
    price: '330',
    maxGuests: '',
    imgURL: 'https://images.unsplash.com/photo-1444201983204-c43cbd584d93?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
    descriptionShort: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...',
    descriptionLong: 'Feugiat in fermentum posuere urna nec tincidunt praesent semper feugiat. Sed ullamcorper morbi tincidunt ornare. In ornare quam viverra orci sagittis eu volutpat odio facilisis. Viverra accumsan in nisl nisi scelerisque. Amet luctus venenatis lectus magna. Suspendisse in est ante in. Cras adipiscing enim eu turpis egestas pretium aenean. Condimentum vitae sapien pellentesque habitant morbi. Massa id neque aliquam vestibulum morbi blandit cursus. Sed faucibus turpis in eu mi. Mattis nunc sed blandit libero volutpat. Id diam maecenas ultricies mi eget mauris. Pretium lectus quam id leo. Laoreet non curabitur gravida arcu ac tortor. Pretium viverra suspendisse potenti nullam. Mi sit amet mauris commodo quis imperdiet massa. Sem viverra aliquet eget sit amet tellus. Velit euismod in pellentesque massa placerat duis ultricies lacus',
    address: '',
    long: '',
    lat: '',
    stars: 'four',
    icons: ['fa-solid fa-tv', 'fa-solid fa-shower', 'fa-solid fa-wheelchair-move', 'fa-solid fa-wifi'],
  }, {
    id: '03',
    name: 'the-dolor-inn',
    type: 'Hotel',
    iconOne: '',
    txtOne: '',
    iconTwo: '',
    txtTwo: '',
    email: '',
    price: '',
    maxGuests: '',
    imgURL: 'https://images.unsplash.com/photo-1445991842772-097fea258e7b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
    description: '',
    address: '',
    long: '',
    lat: '',
    stars: 'three',
  }, {
    id: '04',
    name: 'the-consectetur',
    type: 'Cabin',
    iconOne: '',
    txtOne: '',
    iconTwo: '',
    txtTwo: '',
    email: '',
    price: '',
    maxGuests: '',
    imgURL: 'https://images.unsplash.com/photo-1644057501622-dfa7dd26dbfb?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1081&q=80',
    description: '',
    address: '',
    long: '',
    lat: '',
    stars: 'two',
  }, {
    id: '05',
    name: 'the-adipiscing',
    type: 'Lodge',
    iconOne: '',
    txtOne: '',
    iconTwo: '',
    txtTwo: '',
    email: 'lorem@inn.com',
    price: '330',
    maxGuests: '4',
    imgURL: 'https://images.unsplash.com/photo-1496417263034-38ec4f0b665a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1171&q=80',
    descriptionShort: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...',
    descriptionLong: 'Feugiat in fermentum posuere urna nec tincidunt praesent semper feugiat. Sed ullamcorper morbi tincidunt ornare. In ornare quam viverra orci sagittis eu volutpat odio facilisis. Viverra accumsan in nisl nisi scelerisque. Amet luctus venenatis lectus magna. Suspendisse in est ante in. Cras adipiscing enim eu turpis egestas pretium aenean. Condimentum vitae sapien pellentesque habitant morbi. Massa id neque aliquam vestibulum morbi blandit cursus. Sed faucibus turpis in eu mi. Mattis nunc sed blandit libero volutpat. Id diam maecenas ultricies mi eget mauris. Pretium lectus quam id leo. Laoreet non curabitur gravida arcu ac tortor. Pretium viverra suspendisse potenti nullam. Mi sit amet mauris commodo quis imperdiet massa. Sem viverra aliquet eget sit amet tellus. Velit euismod in pellentesque massa placerat duis ultricies lacus',
    description: '',
    address: '',
    location: 'Bergen city center',
    long: '',
    lat: '',
    stars: 'one',
  },
]